# The URL for your Discord Webhook.
# This cannot be empty!
webhookUrl: ""

# IF YOU DON'T KNOW ANYTHING ABOUT WEBHOOK STRUCTURE, PLEASE GO HERE: https://gist.github.com/Birdie0/78ee79402a4301b1faf412ab5f1cdcf9#structure-of-webhooks

# TODO
onServerStart:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\":,
                \"description:\": \"\" 
              }
            ]
          }"

# TODO
onServerStop:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\":,
                \"description:\": \"\" 
              }
            ]
          }"

onPlayerJoin:
  # Available variables:
  # - %player% - player who joined
  # - %time% - server's local time
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** joined the game.\", 
                \"color\": 3066993
              }
            ]
          }"

onPlayerQuit:
  # Available variables:
  # - %player% - player who left
  # - %time% - server's local time
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** left the game.\",
                \"color\": 16711680
              }
            ]
          }"

onPlayerKicked:
  # Available variables:
  # - %player% - player who left
  # - %time% - server's local time
  # - %reason% - reason provided
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** was kicked: *%reason%*\",
                \"color\": 16753920
              }
            ]
          }"

onPlayerDeath:
  # This event is different.
  # Message for a player dying from an NPC and a player are different.

  # Available variables:
  # - %player% - player who left
  # - %time% - server's local time
  # - %deathMessage% - death message visible in chat
  # - %newLevel% - player's level after death
  # - %newExp% - player's experience after death
  # - %oldLevel% - player's level before dying
  # - %oldExp% - player's experience before dying
  playerKilledByNPC:
    announce: true
    messageJson: "{
              \"embeds\": [
                {
                  \"color\": 16711680,
                  \"description:\": \"\" 
                }
              ]
            }"
  playerKilledByPlayer:
    # Additional variables:
    # - %killer% - killer's player name
    announce: true
    messageJson: "{
              \"embeds\": [
                {
                  \"color\": 16711680,
                  \"description:\": \"[%time%] **%player%** was killed by **%killer%**\" 
                }
              ]
            }"

onPlayerChat:
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] ***%player%***: %message%\",
                \"color\": 3447003
              }
            ]
          }"

onPlayerAdvancementComplete:
  # Available variables:
  # - %player% - player name
  # - %time% - server's local time
  # - %advancement% - advancement name visible in game
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** has made the advancement [**%advancement%**]\", 
                \"color\": 16776960
              }
            ]
          }"

#END OF FILE
