# The URL for your Discord Webhook.
# This cannot be empty!
webhookUrl: ""

# IF YOU DON'T KNOW ANYTHING ABOUT WEBHOOK STRUCTURE, PLEASE GO HERE: https://gist.github.com/Birdie0/78ee79402a4301b1faf412ab5f1cdcf9#structure-of-webhooks

# TODO
onServerStart:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\":,
                \"description:\": \"\" 
              }
            ]
          }"

# TODO
onServerStop:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\":,
                \"description:\": \"\" 
              }
            ]
          }"

onPlayerJoin:
  # Available variables:
  # %player% - player who joined
  # %time% - server's local time
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** joined the game.\", 
                \"color\": 3066993
              }
            ]
          }"

onPlayerQuit:
  # Available variables:
  # %player% - player who left
  # %time% - server's local time
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** left the game.\",
                \"color\": 16711680
              }
            ]
          }"

onPlayerKicked:
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** was kicked: *%reason%*\",
                \"color\": 16753920
              }
            ]
          }"

# TODO
onPlayerDeath:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\": 16711680,
                \"description:\": \"\" 
              }
            ]
          }"

onPlayerChat:
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] ***%player%***: %message%\",
                \"color\": 3447003
              }
            ]
          }"

onPlayerAdvancementComplete:
  # Available variables:
  # %player% - player name
  # %time% - server's local time
  # %advancement% - advancement name visible in game
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"description\": \"[%time%] **%player%** has made the advancement [**%advancement%**]\", 
                \"color\": 16776960
              }
            ]
          }"

#END OF FILE
