# The URL for you Discord Webhook.
# This cannot be empty!
webhookUrl: ""

# IF YOU DON'T KNOW ANYTHING ABOUT WEBHOOK STRUCTURE, PLEASE GO HERE: https://gist.github.com/Birdie0/78ee79402a4301b1faf412ab5f1cdcf9#structure-of-webhooks

# TODO
onServerStart:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\":,
                \"description:\": \"\" 
              }
            ]
          }"

# TODO
onServerStop:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\":,
                \"description:\": \"\" 
              }
            ]
          }"

onPlayerJoin:
  # Available variables:
  # %player% - player who joined
  # %time% - server's local time

  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"color\": 3066993,
                \"description:\": \"[%time%] **%player%** joined the game.\" 
              }
            ]
          }"

onPlayerQuit:
  # Available variables:
  # %player% - player who left
  # %time% - server's local time
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"color\": 16711680,
                \"description\": \"[%time%] **%player%** left the game.\"
              }
            ]
          }"

onPlayerKicked:
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"color\": 16711680,
                \"description\": \"[%time%] **%player%** was kicked: *%reason%*\"
              }
            ]
          }"

# TODO
onPlayerDeath:
  announce: false
  messageJson: "{
            \"embeds\": [
              {
                \"color\": 16711680,
                \"description:\": \"\" 
              }
            ]
          }"

onPlayerChat:
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"color\": 16711680,
                \"description\": \"[%time%] ***%player%***: %message%\"
              }
            ]
          }"

onPlayerAdvancementComplete:
  announce: true
  messageJson: "{
            \"embeds\": [
              {
                \"color\": 16776960,
                \"description:\": \"[%time%] **%player%**\" 
              }
            ]
          }"


