
#Your webhook URL to send messages to
#This can`t be empty.
webhookUrl: ""

# stuff to announce
# true - send messages
# false - ignore
announceAdvancements: true
announcePlayerDeaths: true
announcePlayerKills: true
announceChatMessages: true

announceServerStart: true
announceServerStop: true

announcePlayerJoin: true
announcePlayerQuit: true
announcePlayerKicks: true

# prevent players from using @everyone and @here
preventPingsAndTags: false

  ########################################
  ############# PLACEHOLDERS #############
  ########################################

  # %player% - player name
  # %message% - raw message sent
  # %killer% - player who killed someone (ONLY WORKING IN PLAYER KILL MESSAGES IF THE PLAYER DIES FROM ANOTHER PLAYER)
  # %weapon% - meta name of the weapon the killer used (if any)
  # %advancement% - the advancement the player unlocked
  # %time% - server time (from computer)

    # EXCLUSIVE VARIABLES:
    # - %reason% - exclusive to:
    #   - PlayerKickEvent
    #
    # - %killer% - exclusive to:
    #   - PlayerKilledEvent
    #
    # - %weapon% - exclusive to:
    #   - PlayerKilledEvent
    #
    # - %advancement% - exclusive to:
    #   - PlayerAdvancementEvent

#JOIN EVENT
onPlayerJoinEventMessage: '[%time%] **%player%** joined the server.'

#HAS TO BE A DECIMAL NUMBER
onPlayerJoinEventEmbedColor: 3066993


#QUIT EVENT
onPlayerQuitEventMessage: '[%time%] **%player%** left the server.'

#HAS TO BE A DECIMAL NUMBER
onPlayerQuitEventEmbedColor: 16711680


#CHAT MESSAGE EVENT
chatEventMessage: '[%time%] ***%player%:*** **%message%**'

#WHEN USING /send
onCommandForceMessageEmbedColor: 65535

#HAS TO BE A DECIMAL NUMBER
chatEventEmbedColor: 65535


#PLAYER KICKED EVENT
playerKickMessage: '[%time%] **%player%** was kicked: *%reason%*'
playerKickEmbedColor: 15158332
#PLAYER DEATH EVENT

#this message is only used when player died to an NPC (e.g. zombie) or natural causes (hunger/fall damage)
playerDeathEventMessage: '[%time%] **%player%** died.'
playerDeathEventEmbedColor: 16711680


#PLAYER KILLED EVENT
playerKilledEventMessage: '[%time%] **%player%** was killed by **%killer%**'
playerKilledEventEmbedColor: 16711680

#ONLY WHEN KILLER'S ITEM HAD A SPECIAL NAME
playerKilledByWeaponEventMessage: '[%time%] **%player%** was killed by **%killer%** using *%weapon%*'
playerKilledByWeaponEmbedColor: 16711680


#PLAYER ADVANCEMENT EVENT
playerAdvancementEvent: '[%time%] **%player%** achieved **%advancement%**'
playerAdvancementEventEmbedColor: 16776960

#END OF FILE