name: WebhookIntegrations
version: '${project.version}'
main: rudynakodach.github.io.webhookintegrations.WebhookIntegrations
api-version: 1.17
commands:

  seturl:
    usage: /setUrl <url>
    permission: webhookintegrations.setwebhookurl
  send:
    usage: /send <isEmbed> <message>
    permission: webhookintegrations.send

  cfgreload:
    usage: /wi config reset <confirm>
    permission: webhookintegrations.config.reset

  reload:
    usage: /wi reload
    permission: webhookintegrations.reload

  wi:
    usage: /wi
    permission: webhookintegrations.wi

  update:
    usage: /wi update
    permission: webhookintegrations.update

  analyze:
    usage: /wi analyze
    permission: webhookintegrations.analyze

  disable:
    usage: /wi disable
    permission: webhookintegrations.disable

  enable:
    usage: /wi enable
    permission: webhookintegrations.enable

  setLang:
    usage: /wi setlanguage
    permission: webhookintegrations.setlanguage